### ISSUE TITLE
Bootstrap doesn't work

### ISSUE THREAD

**Issue by DylanFPS** [AzyIsCool/Click-To-Website#1]
Good job on the Materialize though, great C# practice haha. Anyway bootstrap doesn't work, it just shows a blank form.

**Comment by AzyIsCool** [comment]
It because I haven't started the bootstrap part yet, I just added the form so it there when I start work on it

**Comment by DylanFPS** [comment]
Alright. You should at least disable the relevant GUI elements until it's been added ;)
