### ISSUE TITLE
You can't see the icon in the task bar.

### ISSUE THREAD

**Issue by DylanFPS** [AzyIsCool/Click-To-Website#2]
Using some color schemes, the black CTW logo that you use in the form Icon property can't be seen.

- Example: Using the default black color scheme in Windows 10, the logo cannot be seen
- Potential Solution: Add a white Outer Glow around the logo

**Comment by DylanFPS** [comment]
The potential solution will work on most, if not all, color schemes

**Comment by AzyIsCool** [comment]
Thanks for pointing this out, I have just done that change now.
